#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202605130000-git
# @@Author           :  Jason Hempstead
# @@Contact          :  git-admin@casjaysdev.pro
# @@ReadME           :  no-ai-attribution.sh --help
# @@Copyright        :  Copyright: (c) 2026 Jason Hempstead, Casjays Developments
# @@Created          :  Tuesday, May 13, 2026 00:00 EDT
# @@File             :  no-ai-attribution.sh
# @@Description      :  Claude Code PreToolUse hook - block AI attribution phrases in written content
# @@Changelog        :  Initial version
# @@TODO             :  See project issues
# @@Other            :  Fires on Write and Edit tool use; blocks attribution trailers/comments only
# @@Resource         :  github.com/casapps/claude-code-hooks
# @@Terminal App     :  no
# @@sudo/root        :  no
# @@Template         :  bash/simple
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# shellcheck disable=SC1001,SC1003,SC2001,SC2003,SC2016,SC2031,SC2090,SC2115,SC2120,SC2155,SC2199,SC2229,SC2317,SC2329
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
VERSION="202605130000-git"
# - - - - - - - - - - - - - - - - - - - - - - - - -
set -uo pipefail
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Patterns that constitute AI attribution. Match only phrases where an AI
# tool is credited as the author/generator — NOT bare product names used
# in documentation, filenames, or tool references.
#
# Blocked examples:
#   Generated by Claude        Co-Authored-By: Claude
#   Written by Anthropic       Generated with Claude Code
#   Created by AI              🤖 Generated
#   AI-generated content       This file was generated by Claude
#
# NOT blocked:
#   CLAUDE.md (filename)       Claude Code hook
#   Using Claude               Anthropic API docs
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
ATTRIBUTION_PATTERN='(generated|written|created|authored)[[:space:]]+(by|with)[[:space:]]+(claude|anthropic|an? ai\b)|co-authored-by:[[:space:]]*(claude|anthropic)|co_authored_by:[[:space:]]*(claude|anthropic)|\bai[- ]generated\b|🤖[[:space:]]*(generated|created|written|authored)|(this[[:space:]]+file[[:space:]]+(was|is)[[:space:]]+(generated|written|created)[[:space:]]+by[[:space:]]+(claude|anthropic|ai\b))'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
__require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf 'no-ai-attribution.sh: required command not found: %s\n' "$1" >&2
    exit 0
  fi
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
__extract_content() {
  python3 -c '
import json, sys
try:
    d = json.load(sys.stdin).get("tool_input", {})
    # Write tool uses "content"; Edit tool uses "new_string"
    print(d.get("content") or d.get("new_string") or "")
except Exception:
    print("")
'
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
__require_cmd python3
__require_cmd grep
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
INPUT="$(cat)"
CONTENT="$(printf '%s' "$INPUT" | __extract_content)"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[ -z "$CONTENT" ] && exit 0
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
if printf '%s' "$CONTENT" | grep -qiE "$ATTRIBUTION_PATTERN"; then
  printf 'BLOCKED: AI attribution phrase detected in file content.\n' >&2
  printf 'Remove lines like "Generated by Claude", "Co-Authored-By: Claude", or "AI-generated".\n' >&2
  exit 2
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
exit 0
